LOGIN_Assig/urls.py
from django.urls import path
from LOGIN_Assig.views import *

app_name = "LOGIN_Assig"

urlpatterns = [
    path("", login, name="login"),
    path("registration", registration, name="registration"),
    path("home", home, name="home"),
    path("profile", profile, name="profile"),
    path("saveData", saveData, name="saveData"),
    path("toDoListDelete", toDoListDelete, name="toDoListDelete"),
    path("workDone", workDone, name="workDone"),
    path("logout", logout, name="logout"),
]

OS/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.views.static import serve
from django.conf.urls.static import static

urlpatterns = [
    path("admin", admin.site.urls),
    path("", include("LOGIN_Assig.urls")),
    re_path(r"^media/(?P<path>.*)$", serve, {"document_root": settings.MEDIA_ROOT}),
    re_path(r"^static/(?P<path>.*)$", serve, {"document_root": settings.STATIC_ROOT}),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

LOGIN_Assig/models.py
from django.db import models


class User(models.Model):
    username = models.CharField(max_length=50, primary_key=True)
    fullName = models.CharField(null=False, max_length=30)
    password = models.CharField(null=False, max_length=20)
    loginTimes = models.IntegerField(default=0)

    def __str__(self):
        return str(self.username)


class ToDoList(models.Model):
    toDoListId = models.BigAutoField(primary_key=True, auto_created=True)
    Username = models.ForeignKey(User, on_delete=models.CASCADE)
    data = models.CharField(null=True, max_length=500)
    status = models.BooleanField(default=False)
    date = models.DateField(auto_now=True)

    def __str__(self):
        return str(self.Username.username)

LOGIN_Assig/views.py
from django.shortcuts import render
from LOGIN_Assig.models import *
from datetime import datetime
from django.utils import timezone


def login(request):
    if request.method == "POST":
        username = request.POST["username"]
        password = request.POST["password"]
        userN = User.objects.filter(username=username)
        if len(userN) == 0:
            loginError = "Invalid email or password"
            return render(request, "login.html", {"loginError": loginError})
        # elif len(userN):
        else:
            user = User.objects.filter(username=username, password=password)
            if len(user) == 0:
                newUser = User()
                newUser.username = userN.first().username
                newUser.password = userN.first().password
                newUser.fullName = userN.first().fullName
                if userN.first().loginTimes >= 5:
                    newUser.loginTimes = 0
                else:
                    newUser.loginTimes = userN.first().loginTimes + 1
                loginTimes = newUser.loginTimes
                print("Time ...", newUser.loginTimes)
                newUser.save()
                return render(request, "login.html", {"loginTimes": str(loginTimes)})
            else:
                newUser = User()
                newUser.username = userN.first().username
                newUser.password = userN.first().password
                newUser.fullName = userN.first().fullName
                newUser.loginTimes = 0
                newUser.save()
                request.session["username"] = user.first().username
                request.session["fullName"] = user.first().fullName
                return home(request)
    else:
        if "username" not in request.session.keys():
            return render(request, "login.html")
        else:
            return home(request)


def home(request):
    if "username" not in request.session.keys():
        return render(request, "login.html")
    else:
        toDoLists = ToDoList.objects.filter(Username=request.session["username"])
        context = {
            "toDoLists": toDoLists,
        }
        return render(request, "home.html", context)


def saveData(request):
    if "username" not in request.session.keys():
        return render(request, "login.html")
    if request.method == "POST":
        userData = ToDoList()
        userData.Username = User.objects.get(username=request.session["username"])
        userData.data = request.POST["data"]
        userData.save()
    return home(request)


def toDoListDelete(request):
    if "username" not in request.session.keys():
        return render(request, "login.html")
    else:
        toDoList = 0
        try:
            toDoList = ToDoList.objects.filter(
                toDoListId=request.POST["toDoListId"]
            ).first()
        except:
            try:
                toDoList = ToDoList.objects.filter(
                    toDoListId=request.GET["toDoListId"]
                ).first()
            except:
                pass
        if toDoList:
            toDoList.delete()
    return home(request)


def workDone(request):
    if "username" not in request.session.keys():
        return render(request, "login.html")
    else:
        toDoList = 0
        try:
            toDoList = ToDoList.objects.filter(
                toDoListId=request.POST["toDoListId"]
            ).first()
        except:
            try:
                toDoList = ToDoList.objects.filter(
                    toDoListId=request.GET["toDoListId"]
                ).first()
            except:
                pass
        if toDoList:    
            doList = ToDoList()
            doList.toDoListId = toDoList.toDoListId
            doList.Username = User.objects.get(username=request.session["username"])
            doList.data = toDoList.data
            doList.status = True
            doList.data = doList.data
            doList.save()
    return home(request)


def registration(request):
    if request.method == "POST":
        username = request.POST["username"]
        if len(User.objects.filter(username=username)):
            userStatus = 1
        else:
            user = User()
            user.username = request.POST["username"]
            user.fullName = request.POST["name"]
            user.password = request.POST["password"]
            user.save()
            return render(request, "login.html")
    else:
        return render(request, "registration.html")


def profile(request):
    if "username" not in request.session.keys():
        return render(request, "login.html")
    return home(request)


def logout(request):
    if "email" in request.session.keys():
        del request.session["username"]
        del request.session["fullName"]
    return render(request, "login.html")

LOGIN_Assig/templates/home.html
{% extends "master.html" %}
{% load static %}

{% block menu %}
<a href="{% url 'LOGIN_Assig:profile' %}">Profile</a>
<a href="{% url 'LOGIN_Assig:logout' %}">Logout</a>
{% endblock %}

{% block content %}
<h1 class="centre-text">Welcome {{ request.session.fullName | upper}}, to your Dashboard. </h1><br>

<div class="box">
    <div class="left">
        <form action="{% url 'LOGIN_Assig:saveData' %}" method="post">
            {% csrf_token %}
            <input type="text" id="inputBox" autofocus name="data" placeholder="Enter Do List">
            <button type="submit" id="save-data"> <i class="fa-solid fa-arrow-right"></i></button>
        </form>
        <ul class="toDoList">
            {% for toDoList in toDoLists %}
            <hr>
            <li>
                <p class="listData"><b>{{toDoList.toDoListId}}. </b>
                    {{toDoList.date}} ,
                    {{toDoList.data}}
                </p>
                <div class="btns">
                    <form style="display: none;" action="{% url 'LOGIN_Assig:workDone' %}" method="post">
                        {% csrf_token %}
                        <input type="hidden" id="status" autofocus name="toDoListId">
                        <button type="submit" id="save-status"> <i class="fa-solid fa-arrow-right"></i></button>
                    </form>
                    {% if toDoList.status %}
                    <i class="fa-solid fa-circle-check" style="color: #00c227;"></i>
                    {% else %}
                    <a href="{% url 'LOGIN_Assig:workDone' %}?toDoListId={{toDoList.toDoListId}}">☑️</a>
                    {% endif %}
                    <form style="display: none;" action="{% url 'LOGIN_Assig:toDoListDelete' %}" method="post">
                        {% csrf_token %}
                        <input type="hidden" id="deleteData" autofocus name="toDoListId">
                        <button type="submit" id="delete-data"> <i class="fa-solid fa-arrow-right"></i></button>
                    </form>
                    <a href="{% url 'LOGIN_Assig:toDoListDelete' %}?toDoListId={{toDoList.toDoListId}}"><i
                            class="fa-solid fa-trash" style="color: #ff0000;"></i></a>
                </div>
            </li>
            {% endfor %}
            <hr>
        </ul>
    </div>
    <div class="right">
        <h2>Voice Command</h2>
        <hr>
        <div class="command-component">
            <div class="mic-system">
                <button id="startBtn">
                    <img id="img" src="{% static 'img/micpic.jpg' %}" alt="micpic">
                    <video id="vid" src="{% static 'img/micgif.mp4' %}" loop muted autoplay></video>
                </button>
                <hr>
                <h3 id="statusText">Heard :</h3>
                <hr>
            </div>
            <div class="command">
                (Example) Say :
                <hr>
                <ul>
                    <li>"New Task buy milk" </li>
                    <li>"Delete task 2" </li>
                    <li>"Mark Task 1"</li>
                </ul>
            </div>
        </div>
    </div>
</div>
<script src="{% static 'script.js' %}"></script>

{% endblock %}

LOGIN_Assig/templates/login.html
{% extends "master.html" %}

{% block menu %}
<a href="{% url 'LOGIN_Assig:registration' %}">Register</a>
{% endblock %}

{% block content %}
<div class="login-container">
    <h1 class="centre-text">Login Here</h1>

    {% if loginError %}
    <h4>
        <p>{{loginTimes}}</p>
        <p class="centre-text">{{loginError}}</p>
    </h4>
    {% endif %}
    <form action="{% url 'LOGIN_Assig:login' %}" method="post">
        {% csrf_token %}
        <div class="input-group">
            <label for="username">UserName</label>
            <input type="text" name="username" id="username" minlength="6" maxlength="20" required
                placeholder="Enter your UserName">
        </div>

        <div class="input-group">
            <label for="password">Password</label>
            <div class="password-wrapper">
                <input type="password" name="password" minlength="6" maxlength="20" id="password" required
                    placeholder="Enter your password">
                <span class="toggle-password" onclick="togglePassword()">👁</span>
            </div>
        </div>
        <p class="centre-text" style="color: red;" id="freez-sms"></p>
        <p class="centre-text" id="freez"></p>

        {% if loginError %}
        <a class="centre-text" href="{% url 'LOGIN_Assig:login' %}">Forget Password</a>
        {% endif %}

        <button type="submit" class="login-btn">Login</button>

        {% if loginTimes >= "5" %}
        <script>
            console.log("loginFreez");
            document.querySelector("#freez-sms").innerText = "⏳ Login is temporarily locked. Try again in 00:30 seconds.";
            let username = document.querySelector("#username");
            let password = document.querySelector("#password");
            let btn = document.querySelector(".login-btn");
            username.disabled = true;
            password.disabled = true;
            btn.disabled = true;

            let min = 0;
            let sec = 30;
            let t = setInterval(() => {
                sec--;
                if (sec == -1) {
                    if (min == 0 && sec == -1) {
                        sec--;
                        username.disabled = false;
                        password.disabled = false;
                        btn.disabled = false;
                        document.querySelector("#freez-sms").innerText = "";
                        clearTimeout(t);
                        sec = 0;
                        min = 0;
                    }
                    else {
                        min--;
                        sec = 59;
                    }
                }
                document.querySelector("#freez").innerText = sec;
                console.log(sec);
            }, 1000);
            document.querySelector("#freez").innerText = "";
        </script>
        {% endif %}

    </form>
    <p class="login-text">Don't have an account? <a href="{% url 'LOGIN_Assig:registration' %}">Register</a></p>
</div>
<script>
    function togglePassword() {
        let passwordInput = document.getElementById("password");
        if (passwordInput.type === "password") {
            passwordInput.type = "text";
        } else {
            passwordInput.type = "password";
        }
    }
</script>

{% endblock %}

LOGIN_Assig/templates/master.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>To-Do-List </title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link rel="stylesheet" href="{% static 'login.css' %}">
    <!-- <link rel="stylesheet" href="{% static 'profile.css' %}"> -->
</head>

<body>
    <header>
        <div class="logo-name"><a href="{% url 'LOGIN_Assig:home' %}">
            <h1>To-Do-List</h1>
        </a>
        </div>
        <div class="menu">
            {% block menu %}

            {% endblock %}
        </div>
    </header>
    <main>
        <section>
            <div class="content">
                {% block content %}

                {% endblock %}
            </div>
        </section>
    </main>
    <!-- <script src="{% static 'js/app.js' %}"></script> -->
</body>

</html>

LOGIN_Assig/templates/registration.html
{% extends "master.html" %}
{% load static %}

{% block menu %}
<a href="{% url 'LOGIN_Assig:login' %}">Login</a>
{% endblock %}

{% block content %}
<div class="login-container">
    <h2>Create an Account</h2>
    {% if userStatus == 1 %}
    <p class="centre-text"> Sorry, email registered, please try different email.</p>
    {% elif userStatus == 4 %}
    <p class="centre-text"> Opps!! Password and confirm password are different.</p>
    {% elif userStatus == 5 %}
    <p class="centre-text"> Please choose a stronger password. Try a mix of letters(capital and small), numbers and
        symbols.</p>
    {% endif %}
    <form action="{% url 'LOGIN_Assig:registration' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="input-group">
            <label for="username">UserName</label>
            <input type="text" name="username" id="username" required placeholder="Enter your UserName">
        </div>
        
        <div class="input-group">
            <label for="name">FullName</label>
            <input type="text" name="name" id="name" required placeholder="Enter your FullName">
        </div>

        <div class="input-group">
            <label for="password">Password</label>
            <div class="password-wrapper">
                <input type="password" name="password" id="password" required placeholder="Enter your password">
                <span class="toggle-password" onclick="togglePassword()">👁</span>
            </div>
        </div>

        <button type="submit" class="login-btn">Submit</button>
        <p class="login-text">Already have an account? <a href="{% url 'LOGIN_Assig:login' %}">Login here</a></p>
    </form>
</div>
<script>
    function togglePassword() {
        let passwordInput = document.getElementById("password");
        if (passwordInput.type === "password") {
            passwordInput.type = "text";
        } else {
            passwordInput.type = "password";
        }
    }
</script>

{% endblock %}